###consul服务端口号
server:
  port: 8007

spring:
  application:
    name: consul-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/the_course?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: aaaaaa
####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.top.cloud.api.common.entities    # 所有Entity别名类所在包